### ISSUE TITLE
На плате MURMULATORA с PSRAM  лаунчер не работает 

### ISSUE THREAD

**Issue by billgilbert7000** [xrip/pico-launcher#5]
На плате MURMULATORA с PSRAM  не читается SD карта в лаунчере
_Если удалить  опрос NES Gamepad'а из кода  то лаунчер начинает работать._
//  nespad_read(); // ???
При этом на плате без PSRAM эта же pico RP2040  с лаунчером работает нормально
PSRAM подключенно так :
        PSRAM_PIN_CS=18
        PSRAM_PIN_SCK=19
        PSRAM_PIN_MOSI=20
        PSRAM_PIN_MISO=21
Джойстики вообще не подключены.

**Comment by xrip** [comment]
Нужно больше информации. Какая версия платы? Почему джойстики во множественном числе, когда на плате мурмулятора один джойстик? 
У меня все платы: 1.2 с псрам на проводах, 1.3 с псрам и 1.4 с псрам и I2S DAC работаю со всей подключенной переферией.
Кроме того, в коде лончера нет ни строчки кода, который хоть как то мог трогать пины под ПСРАМ.

Смею предположить что проблема в железе, возможно где то КЗ, не достаточная ёмкость/не припаян конденсатор по питанию СД и джойстика. В любом случае, это стоить обсуждать например в группе мурмулятора в TG

https://t.me/ZX_MURMULATOR

**Comment by billgilbert7000** [comment]
Да Вы правы! Проблема была в припаянном наоборот  стабилитроне GPIO16 (линия данных NES Gamepad'а) из-за чего был всегда низкий уровень на этом входе.  Поэтому опрос джойстика работал некорректно.  После исправления этой неисправности лаунчер прекрасно работает.
